export interface FamousProfile {
  slug: string;
  name: string;
  born: string;
  knownFor: string;
  archetype: 'strategic_commander' | 'nurturing_creative' | 'harmonizer_guardian' | 'steady_achiever';
  element: 'Metal' | 'Wood' | 'Fire' | 'Earth' | 'Water';
  trait: string;
  quote: string;
  whyTheyEmbody: string;
}

const profiles: FamousProfile[] = [
  {
    slug: 'taylor-swift',
    name: 'Taylor Swift',
    born: '1989-12-13',
    knownFor: 'Singer-songwriter, 14 Grammy Awards',
    archetype: 'nurturing_creative',
    element: 'Fire',
    trait: 'Masterful storytelling, reinvention as artistic expression',
    quote: "I'm the problem, it's me.",
    whyTheyEmbody: "Taylor Swift's career is a masterclass in turning personal experience into universal art. Her Fire element channels emotional intensity into creative output that resonates across cultures.",
  },
  {
    slug: 'rihanna',
    name: 'Rihanna',
    born: '1988-02-20',
    knownFor: 'Singer, Fenty Beauty founder, 9 Grammy Awards',
    archetype: 'nurturing_creative',
    element: 'Fire',
    trait: 'Bold reinvention, turning vulnerability into global brands',
    quote: 'I think the most heroic thing you can do is grow up.',
    whyTheyEmbody: "Rihanna's Fire element burns bright and transforms. She turned personal struggles into global empires, showing how Nurturing Creative energy channels emotion into creation.",
  },
  {
    slug: 'kanye-west',
    name: 'Kanye West',
    born: '1977-06-08',
    knownFor: 'Rapper, producer, fashion designer',
    archetype: 'nurturing_creative',
    element: 'Fire',
    trait: 'Revolutionary vision, turning disruption into art',
    quote: 'I am Warhol. I am the number one artist in the world.',
    whyTheyEmbody: "Kanye's Fire element burns through conventions. His Nurturing Creative archetype expresses through relentless creative reinvention.",
  },
  {
    slug: 'drake',
    name: 'Drake',
    born: '1986-10-24',
    knownFor: 'Rapper, singer, actor',
    archetype: 'steady_achiever',
    element: 'Water',
    trait: 'Strategic evolution, emotional intelligence as competitive advantage',
    quote: "Started from the bottom, now we're here.",
    whyTheyEmbody: "Drake's Water element flows through emotional depth and strategic patience. His Steady Achiever archetype builds empires through authenticity and vulnerability.",
  },
  {
    slug: 'justin-trudeau',
    name: 'Justin Trudeau',
    born: '1971-12-25',
    knownFor: 'Canadian Prime Minister',
    archetype: 'harmonizer_guardian',
    element: 'Water',
    trait: 'Bridge-building through emotional intelligence, grace under scrutiny',
    quote: 'Canada is back.',
    whyTheyEmbody: "Trudeau's Water element flows through his communication style. His Harmonizer Guardian archetype uses empathy as political strategy.",
  },
  {
    slug: 'isaac-newton',
    name: 'Isaac Newton',
    born: '1643-01-04',
    knownFor: 'Physicist, mathematician, Principia Mathematica',
    archetype: 'steady_achiever',
    element: 'Metal',
    trait: 'Systematic precision, uncovering laws that govern the universe',
    quote: 'If I have seen further, it is by standing on the shoulders of giants.',
    whyTheyEmbody: "Newton's Metal element gave him the precision to formulate laws. His Steady Achiever nature built knowledge methodically.",
  },
  {
    slug: 'nikola-tesla',
    name: 'Nikola Tesla',
    born: '1856-07-10',
    knownFor: 'Inventor, electrical engineer, AC power system',
    archetype: 'nurturing_creative',
    element: 'Water',
    trait: 'Visionary imagination, inventing futures others could not conceive',
    quote: 'The present is theirs; the future, for which I really worked, is mine.',
    whyTheyEmbody: "Tesla's Water element gave him profound imagination. His Nurturing Creative nature invented technologies that nurtured modern civilization.",
  },
  {
    slug: 'alan-turing',
    name: 'Alan Turing',
    born: '1912-06-23',
    knownFor: 'Computer scientist, Enigma codebreaker, AI pioneer',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'First-principles thinking, breaking unsolvable problems',
    quote: 'Sometimes it is the people no one imagines anything of who do the things that no one can imagine.',
    whyTheyEmbody: "Turing's Metal element gave him precise, logical structure. His Strategic Commander nature broke the Enigma code systematically.",
  },
  {
    slug: 'cleopatra',
    name: 'Cleopatra',
    born: '-0069-01-01',
    knownFor: 'Pharaoh of Egypt, last active ruler of the Ptolemaic Kingdom',
    archetype: 'strategic_commander',
    element: 'Fire',
    trait: 'Political genius, using charm and intellect as tools of empire',
    quote: 'The bee of Egypt is not a harlot, but a builder of kingdoms.',
    whyTheyEmbody: "Cleopatra's Fire element burned with political ambition. Her Strategic Commander nature used diplomacy to hold together an empire.",
  },
  {
    slug: 'william-shakespeare',
    name: 'William Shakespeare',
    born: '1564-04-23',
    knownFor: 'Playwright, poet, author of Hamlet, Romeo and Juliet',
    archetype: 'nurturing_creative',
    element: 'Water',
    trait: 'Deep psychological insight, universal truths through character',
    quote: 'To be, or not to be, that is the question.',
    whyTheyEmbody: "Shakespeare's Water element gave him profound emotional depth. His Nurturing Creative nature created characters that grow in the imagination.",
  },
  {
    slug: 'elon-musk',
    name: 'Elon Musk',
    born: '1971-06-28',
    knownFor: 'Tesla, SpaceX, X (Twitter)',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'First-principles thinking, relentless execution',
    quote: 'The first step is to establish that something is possible; then probability will occur.',
    whyTheyEmbody: "Musk's Metal element gives him decisive, structured ambition. His Strategic Commander nature turns visions into operational reality.",
  },
  {
    slug: 'warren-buffett',
    name: 'Warren Buffett',
    born: '1930-08-30',
    knownFor: 'Berkshire Hathaway, investor',
    archetype: 'steady_achiever',
    element: 'Metal',
    trait: 'Patience as competitive advantage, value investing philosophy',
    quote: 'Be fearful when others are greedy, and greedy when others are fearful.',
    whyTheyEmbody: "Buffett's Metal element reflects disciplined, systematic value investing. His Steady Achiever nature builds wealth through patient compounding.",
  },
  {
    slug: 'serena-williams',
    name: 'Serena Williams',
    born: '1981-09-26',
    knownFor: '23 Grand Slam tennis titles',
    archetype: 'steady_achiever',
    element: 'Metal',
    trait: 'Mental toughness, turning pressure into championship performance',
    quote: 'I genuinely love the game. I think that love keeps me going.',
    whyTheyEmbody: "Williams' Metal element gives her precision and competitive discipline. Her Steady Achiever nature built 23 Grand Slam titles through daily excellence.",
  },
  {
    slug: 'lebron-james',
    name: 'LeBron James',
    born: '1984-12-30',
    knownFor: 'NBA champion, entrepreneur, philanthropist',
    archetype: 'steady_achiever',
    element: 'Water',
    trait: 'Longevity through obsessive preparation, building institutions',
    quote: "I'm going to use all my tools, all my skills, and all my abilities to get the job done.",
    whyTheyEmbody: "James' Water element gives him strategic vision. His Steady Achiever nature builds systems and institutions that outlast his career.",
  },
  {
    slug: 'cristiano-ronaldo',
    name: 'Cristiano Ronaldo',
    born: '1985-02-05',
    knownFor: 'Football GOAT, 5 Ballon d\'Or awards',
    archetype: 'steady_achiever',
    element: 'Fire',
    trait: 'Obsessive self-improvement, relentless work ethic',
    quote: 'Your love for what you do must be bigger than the fear of failure.',
    whyTheyEmbody: "Ronaldo's Fire element fuels his relentless drive. His Steady Achiever nature transforms talent through obsessive preparation.",
  },
  {
    slug: 'marie-curie',
    name: 'Marie Curie',
    born: '1867-11-07',
    knownFor: 'Nobel laureate in Physics and Chemistry',
    archetype: 'steady_achiever',
    element: 'Fire',
    trait: 'Stubborn precision, two-Nobel persistence',
    quote: 'Nothing in life is to be feared, only to be understood.',
    whyTheyEmbody: "Curie's Fire element gave her intense determination. Her Steady Achiever nature pursued truth through methodical persistence.",
  },
  {
    slug: 'leonardo-da-vinci',
    name: 'Leonardo da Vinci',
    born: '1452-04-15',
    knownFor: 'Renaissance polymath, Mona Lisa, flying machines',
    archetype: 'nurturing_creative',
    element: 'Metal',
    trait: 'Insatiable curiosity, beauty in systems',
    quote: 'Learning never exhausts the mind.',
    whyTheyEmbody: "Da Vinci's Metal element gave him precision in observation. His Nurturing Creative nature combined curiosity with technical skill.",
  },
  {
    slug: 'napoleon-bonaparte',
    name: 'Napoleon Bonaparte',
    born: '1769-08-15',
    knownFor: 'French Emperor, military strategist',
    archetype: 'strategic_commander',
    element: 'Earth',
    trait: 'Tactical genius, systems thinking at civilizational scale',
    quote: 'Impossible is a word only to be found in the dictionary of fools.',
    whyTheyEmbody: "Napoleon's Earth element gave him steady authority. His Strategic Commander nature built empires through strategic vision.",
  },
  {
    slug: 'barack-obama',
    name: 'Barack Obama',
    born: '1961-08-04',
    knownFor: '44th US President, Nobel Peace Prize',
    archetype: 'harmonizer_guardian',
    element: 'Metal',
    trait: 'Bridge-builder, grace under pressure',
    quote: 'Change will not come if we wait for some other person or some other time.',
    whyTheyEmbody: "Obama's Metal element gave him disciplined composure. His Harmonizer Guardian nature built bridges across divides.",
  },
  {
    slug: 'angela-merkel',
    name: 'Angela Merkel',
    born: '1954-07-17',
    knownFor: 'German Chancellor, physicist',
    archetype: 'strategic_commander',
    element: 'Wood',
    trait: 'Methodical pragmatist, steady authority',
    quote: 'If you have the right system, things will come by themselves.',
    whyTheyEmbody: "Merkel's Wood element gave her patient thinking. Her Strategic Commander nature navigated crises through analysis.",
  },
  {
    slug: 'bill-gates',
    name: 'Bill Gates',
    born: '1955-10-28',
    knownFor: 'Microsoft co-founder, philanthropist',
    archetype: 'strategic_commander',
    element: 'Wood',
    trait: 'Systems thinker, relentless optimizer',
    quote: 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.',
    whyTheyEmbody: "Gates' Wood element gave him growth-oriented strategy. His Strategic Commander nature created personal computing through systems thinking.",
  },
  {
    slug: 'jeff-bezos',
    name: 'Jeff Bezos',
    born: '1964-01-12',
    knownFor: 'Amazon founder, Blue Origin',
    archetype: 'strategic_commander',
    element: 'Wood',
    trait: 'Long-term thinking, customer obsession',
    quote: 'A brand for a company is like a reputation for a person. You earn reputation by trying to do hard things well.',
    whyTheyEmbody: "Bezos' Wood element gave him patient strategy. His Strategic Commander nature built Amazon through customer obsession.",
  },
  {
    slug: 'mark-zuckerberg',
    name: 'Mark Zuckerberg',
    born: '1984-05-14',
    knownFor: 'Meta (Facebook) founder',
    archetype: 'strategic_commander',
    element: 'Water',
    trait: 'Move fast, own the network',
    quote: 'The biggest risk is not taking any risk.',
    whyTheyEmbody: "Zuckerberg's Water element gives him deep social intuition. His Strategic Commander nature built Facebook through network effects.",
  },
  {
    slug: 'larry-page',
    name: 'Larry Page',
    born: '1973-03-26',
    knownFor: 'Google co-founder',
    archetype: 'strategic_commander',
    element: 'Fire',
    trait: 'Audacious moonshots, first-mover discipline',
    quote: "If you're not doing some things that are crazy, you're not doing enough.",
    whyTheyEmbody: "Page's Fire element gave him bold vision. His Strategic Commander nature turned Google into internet infrastructure.",
  },
  {
    slug: 'lady-gaga',
    name: 'Lady Gaga',
    born: '1986-03-28',
    knownFor: 'Singer, actress, activist',
    archetype: 'nurturing_creative',
    element: 'Fire',
    trait: 'Radical authenticity, art as activism',
    quote: "I'm not a product. I'm not a piece of possession. I'm a human being.",
    whyTheyEmbody: "Gaga's Fire element burns through convention. Her Nurturing Creative nature transforms pain into universal connection.",
  },
  {
    slug: 'steve-jobs',
    name: 'Steve Jobs',
    born: '1955-02-24',
    knownFor: 'Apple co-founder',
    archetype: 'strategic_commander',
    element: 'Wood',
    trait: 'Uncompromising vision, controlled intensity',
    quote: "The people who are crazy enough to think they can change the world are the ones who do.",
    whyTheyEmbody: "Jobs' Wood element gave him relentless growth orientation. His Strategic Commander nature turned Apple into a cultural force through obsessive product focus.",
  },
  {
    slug: 'oprah-winfrey',
    name: 'Oprah Winfrey',
    born: '1954-01-29',
    knownFor: 'Media mogul, philanthropist',
    archetype: 'nurturing_creative',
    element: 'Wood',
    trait: 'Transforming vulnerability into connection',
    quote: 'The biggest adventure you can take is to live the life of your dreams.',
    whyTheyEmbody: "Oprah's Wood element gives her growth-oriented empathy. Her Nurturing Creative nature turns personal vulnerability into universal connection.",
  },
  {
    slug: 'margaret-thatcher',
    name: 'Margaret Thatcher',
    born: '1925-10-13',
    knownFor: 'UK Prime Minister',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'Iron determination, strategic conservatism',
    quote: 'I am not a consensus politician. I am a conviction politician.',
    whyTheyEmbody: "Thatcher's Metal element gave her decisive authority. Her Strategic Commander nature remade Britain through principled determination.",
  },
  {
    slug: 'satya-nadella',
    name: 'Satya Nadella',
    born: '1967-08-19',
    knownFor: 'Microsoft CEO',
    archetype: 'strategic_commander',
    element: 'Fire',
    trait: 'Empathetic leadership, growth mindset',
    quote: 'Empathy is the most important skill you can practice.',
    whyTheyEmbody: "Nadella's Fire element gives him transformational energy. His Strategic Commander nature revived Microsoft through cultural transformation.",
  },
  {
    slug: 'sheryl-sandberg',
    name: 'Sheryl Sandberg',
    born: '1969-08-28',
    knownFor: 'Meta COO, Lean In author',
    archetype: 'strategic_commander',
    element: 'Earth',
    trait: 'Operational excellence, purposeful ambition',
    quote: 'Fortune does not favor the risk-averse.',
    whyTheyEmbody: "Sandberg's Earth element gives her grounded operational skill. Her Strategic Commander nature built Facebook's ad business and championed women's leadership.",
  },
  {
    slug: 'sam-altman',
    name: 'Sam Altman',
    born: '1985-04-22',
    knownFor: 'OpenAI CEO',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'Visionary pragmatist, builder of futures',
    quote: 'The development of full artificial intelligence could spell the end of the human race.',
    whyTheyEmbody: "Altman's Metal element gives him precise strategic vision. His Strategic Commander nature navigates AI development with calculated ambition.",
  },
  {
    slug: 'jensen-huang',
    name: 'Jensen Huang',
    born: '1963-02-17',
    knownFor: 'NVIDIA CEO',
    archetype: 'strategic_commander',
    element: 'Water',
    trait: 'Decade-long bets, platform-level thinking',
    quote: 'Remember, the tortoise won.',
    whyTheyEmbody: "Huang's Water element gives him deep strategic patience. His Strategic Commander nature made decade-long GPU bets that defined the AI era.",
  },
  {
    slug: 'reed-hastings',
    name: 'Reed Hastings',
    born: '1960-10-08',
    knownFor: 'Netflix co-founder',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'Radical candor, freedom and responsibility',
    quote: 'Most people do not really think for themselves.',
    whyTheyEmbody: "Hastings' Metal element gives him systematic thinking. His Strategic Commander nature disrupted Hollywood through long-term platform strategy.",
  },
  {
    slug: 'sundar-pichai',
    name: 'Sundar Pichai',
    born: '1972-06-10',
    knownFor: 'Google CEO',
    archetype: 'strategic_commander',
    element: 'Water',
    trait: 'Patient strategist, consensus builder who executes',
    quote: 'We should be building for the world, not just the West.',
    whyTheyEmbody: "Pichai's Water element gives him adaptive strategic depth. His Strategic Commander nature scaled Android and AI with patient execution.",
  },
  {
    slug: 'winston-churchill',
    name: 'Winston Churchill',
    born: '1874-11-30',
    knownFor: 'UK Prime Minister',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'Defiance as strategy, words as weapons',
    quote: 'We shall fight on the beaches.',
    whyTheyEmbody: "Churchill's Metal element gave him unbreakable resolve. His Strategic Commander nature wielded words as weapons to defeat tyranny.",
  },
  {
    slug: 'peter-thiel',
    name: 'Peter Thiel',
    born: '1967-10-11',
    knownFor: 'PayPal, Palantir, investor',
    archetype: 'strategic_commander',
    element: 'Metal',
    trait: 'Contrarian theses, zero-to-one thinking',
    quote: 'Competition is for losers.',
    whyTheyEmbody: "Thiel's Metal element gives him contrarian precision. His Strategic Commander nature identified secrets others missed and built empires on them.",
  },
  {
    slug: 'michael-jordan',
    name: 'Michael Jordan',
    born: '1963-02-17',
    knownFor: 'NBA champion, entrepreneur',
    archetype: 'steady_achiever',
    element: 'Fire',
    trait: 'Talent is God-given; will is self-made',
    quote: 'I can accept failure, but I cannot accept not trying.',
    whyTheyEmbody: "Jordan's Fire element gave him competitive intensity. His Steady Achiever nature turned talent into championships through relentless preparation.",
  },
  {
    slug: 'dwayne-johnson',
    name: 'Dwayne Johnson',
    born: '1972-05-02',
    knownFor: 'Actor, entrepreneur',
    archetype: 'steady_achiever',
    element: 'Water',
    trait: 'Iron discipline, relentless gratitude',
    quote: 'Be humble. Be hungry.',
    whyTheyEmbody: "Johnson's Water element gives him adaptive resilience. His Steady Achiever nature transformed setbacks into global stardom.",
  },
  {
    slug: 'simone-biles',
    name: 'Simone Biles',
    born: '1997-03-14',
    knownFor: 'Gymnastics GOAT',
    archetype: 'steady_achiever',
    element: 'Fire',
    trait: 'Excellence redefined by mental health',
    quote: 'I should have quit long before Tokyo.',
    whyTheyEmbody: "Biles' Fire element gave her unmatched athletic intensity. Her Steady Achiever nature redefined excellence by protecting her mental health.",
  },
  {
    slug: 'kobe-bryant',
    name: 'Kobe Bryant',
    born: '1978-08-23',
    knownFor: 'NBA champion, entrepreneur',
    archetype: 'steady_achiever',
    element: 'Earth',
    trait: 'Mamba mentality: 4 AM is the advantage',
    quote: 'Everything negative, pressure, challenges, is an opportunity.',
    whyTheyEmbody: "Bryant's Earth element gave him grounded longevity. His Steady Achiever nature built Mamba Mentality into a philosophy of daily excellence.",
  },
  {
    slug: 'nelson-mandela',
    name: 'Nelson Mandela',
    born: '1918-07-18',
    knownFor: 'South African President',
    archetype: 'harmonizer_guardian',
    element: 'Earth',
    trait: 'Forgiveness as revolutionary act',
    quote: 'It always seems impossible until it is done.',
    whyTheyEmbody: "Mandela's Earth element gave him patient moral authority. His Harmonizer Guardian nature chose forgiveness to build a nation.",
  },
  {
    slug: 'mahatma-gandhi',
    name: 'Mahatma Gandhi',
    born: '1869-10-02',
    knownFor: 'Independence movement leader',
    archetype: 'harmonizer_guardian',
    element: 'Earth',
    trait: 'Non-violent resistance, moral force',
    quote: 'Be the change you wish to see in the world.',
    whyTheyEmbody: "Gandhi's Earth element gave him grounded moral authority. His Harmonizer Guardian nature defeated empire through non-violent truth.",
  },
  {
    slug: 'dalai-lama',
    name: 'Dalai Lama',
    born: '1935-07-06',
    knownFor: 'Tibetan spiritual leader',
    archetype: 'harmonizer_guardian',
    element: 'Earth',
    trait: 'Compassion as global practice',
    quote: 'Be kind whenever possible. It is always possible.',
    whyTheyEmbody: "The Dalai Lama's Earth element gives him patient compassion. His Harmonizer Guardian nature embodies mindfulness as global leadership.",
  },
  {
    slug: 'michelle-obama',
    name: 'Michelle Obama',
    born: '1964-01-17',
    knownFor: 'Former First Lady, author',
    archetype: 'harmonizer_guardian',
    element: 'Wood',
    trait: 'When they go low, we go high',
    quote: 'When they go low, we go high.',
    whyTheyEmbody: "Obama's Wood element gives her growth-oriented grace. Her Harmonizer Guardian nature turns personal story into universal inspiration.",
  },
  {
    slug: 'fred-rogers',
    name: 'Fred Rogers',
    born: '1928-03-20',
    knownFor: "Mister Rogers' Neighborhood",
    archetype: 'harmonizer_guardian',
    element: 'Earth',
    trait: 'Every child matters, presence as gift',
    quote: 'You make each day a special place.',
    whyTheyEmbody: "Rogers' Earth element gave him grounded compassion. His Harmonizer Guardian nature proved that presence can transform childhood.",
  },
  {
    slug: 'mother-teresa',
    name: 'Mother Teresa',
    born: '1910-08-26',
    knownFor: 'Humanitarian, saint',
    archetype: 'harmonizer_guardian',
    element: 'Metal',
    trait: 'Service as highest calling',
    quote: 'Not all of us can do great things. But we can do small things with great love.',
    whyTheyEmbody: "Mother Teresa's Metal element gave her disciplined compassion. Her Harmonizer Guardian nature turned service into a global movement.",
  },
  {
    slug: 'princess-diana',
    name: 'Princess Diana',
    born: '1961-07-01',
    knownFor: 'Humanitarian, icon',
    archetype: 'harmonizer_guardian',
    element: 'Metal',
    trait: 'Radical empathy, humanizing power',
    quote: 'The greatest problem in the world is hunger and loneliness.',
    whyTheyEmbody: "Diana's Metal element gave her graceful intensity. Her Harmonizer Guardian nature humanized the British monarchy through radical empathy.",
  },
  {
    slug: 'jacinda-ardern',
    name: 'Jacinda Ardern',
    born: '1980-07-26',
    knownFor: 'New Zealand Prime Minister',
    archetype: 'harmonizer_guardian',
    element: 'Metal',
    trait: 'Compassionate governance, strength in kindness',
    quote: 'I am not a shield for Jacinda Ardern. I am a shield for New Zealand.',
    whyTheyEmbody: "Ardern's Metal element gave her compassionate strength. Her Harmonizer Guardian nature proved that kindness can be political power.",
  },
  {
    slug: 'frida-kahlo',
    name: 'Frida Kahlo',
    born: '1907-07-06',
    knownFor: 'Painter, artist',
    archetype: 'nurturing_creative',
    element: 'Fire',
    trait: 'Raw self-expression, pain as art',
    quote: 'I paint myself because I am often alone and because I am the subject I know best.',
    whyTheyEmbody: "Kahlo's Fire element gave her intense self-expression. Her Nurturing Creative nature turned physical pain into universal art.",
  },
  {
    slug: 'maya-angelou',
    name: 'Maya Angelou',
    born: '1928-04-04',
    knownFor: 'Poet, memoirist',
    archetype: 'nurturing_creative',
    element: 'Earth',
    trait: 'Words that heal, story as liberation',
    quote: 'There is no greater agony than bearing an untold story inside you.',
    whyTheyEmbody: "Angelou's Earth element gave her grounded wisdom. Her Nurturing Creative nature used words to heal collective trauma.",
  },
  {
    slug: 'steve-wozniak',
    name: 'Steve Wozniak',
    born: '1950-08-11',
    knownFor: 'Apple co-founder, engineer',
    archetype: 'nurturing_creative',
    element: 'Metal',
    trait: 'Pure creation for the joy of it',
    quote: 'Never worry about what others say about you. Figure out what you want to become.',
    whyTheyEmbody: "Wozniak's Metal element gave him precise engineering joy. His Nurturing Creative nature built the first Apple for love, not profit.",
  },
  {
    slug: 'walt-disney',
    name: 'Walt Disney',
    born: '1901-12-05',
    knownFor: 'Disney founder',
    archetype: 'nurturing_creative',
    element: 'Metal',
    trait: 'Imagination at industrial scale',
    quote: 'All our dreams can come true, if we have the courage to pursue them.',
    whyTheyEmbody: "Disney's Metal element gave him systematic imagination. His Nurturing Creative nature built entertainment empires from childhood wonder.",
  },
  {
    slug: 'jk-rowling',
    name: 'J.K. Rowling',
    born: '1965-07-31',
    knownFor: 'Harry Potter author',
    archetype: 'nurturing_creative',
    element: 'Wood',
    trait: 'Worlds built from hardship and love',
    quote: 'It is our choices that show what we truly are, far more than our abilities.',
    whyTheyEmbody: "Rowling's Wood element gave her growth-oriented imagination. Her Nurturing Creative nature turned hardship into worlds that nurture millions.",
  },
  {
    slug: 'brene-brown',
    name: 'Brené Brown',
    born: '1965-11-18',
    knownFor: 'Researcher, author',
    archetype: 'nurturing_creative',
    element: 'Wood',
    trait: 'Vulnerability as strength',
    quote: 'Vulnerability is not winning or losing. It is having the courage to show up.',
    whyTheyEmbody: "Brown's Wood element gives her growth-oriented courage. Her Nurturing Creative nature transforms vulnerability into connection.",
  },
  {
    slug: 'coco-chanel',
    name: 'Coco Chanel',
    born: '1883-08-19',
    knownFor: 'Fashion designer',
    archetype: 'nurturing_creative',
    element: 'Earth',
    trait: 'Liberation through elegant simplicity',
    quote: 'Fashion fades, only style remains.',
    whyTheyEmbody: "Chanel's Earth element gave her timeless groundedness. Her Nurturing Creative nature liberated women through elegant simplicity.",
  },
  {
    slug: 'pharrell-williams',
    name: 'Pharrell Williams',
    born: '1973-04-05',
    knownFor: 'Producer, designer',
    archetype: 'nurturing_creative',
    element: 'Water',
    trait: 'Joy as a creative force',
    quote: 'The wider the span, the more reasons to smile.',
    whyTheyEmbody: "Williams' Water element gives him joyful creativity. His Nurturing Creative nature spreads happiness through artistic collaboration.",
  },
  {
    slug: 'tim-burton',
    name: 'Tim Burton',
    born: '1958-08-25',
    knownFor: 'Director',
    archetype: 'nurturing_creative',
    element: 'Earth',
    trait: 'Beauty in darkness, outsider art',
    quote: "One person's craziness is another person's clarity.",
    whyTheyEmbody: "Burton's Earth element gives him grounded darkness. His Nurturing Creative nature finds beauty in what others consider strange.",
  },
  {
    slug: 'eckhart-tolle',
    name: 'Eckhart Tolle',
    born: '1948-02-16',
    knownFor: 'Spiritual teacher, author',
    archetype: 'nurturing_creative',
    element: 'Earth',
    trait: 'Presence as the ultimate creative act',
    quote: 'Realize deeply that the present moment is all you ever have.',
    whyTheyEmbody: "Tolle's Earth element gives him grounded presence. His Nurturing Creative nature teaches that stillness is the ultimate creation.",
  },
  {
    slug: 'beyonce',
    name: 'Beyoncé',
    born: '1981-09-04',
    knownFor: 'Singer, entrepreneur',
    archetype: 'nurturing_creative',
    element: 'Metal',
    trait: 'Disciplined artistry, impeccable craft',
    quote: "I don't like to gamble, but if there is one thing I am sure of, it is this.",
    whyTheyEmbody: "Beyoncé's Metal element gives her disciplined excellence. Her Nurturing Creative nature transforms entertainment into cultural movement.",
  },
  {
    slug: 'carl-jung',
    name: 'Carl Jung',
    born: '1875-07-26',
    knownFor: 'Psychologist, founder of analytical psychology',
    archetype: 'harmonizer_guardian',
    element: 'Wood',
    trait: 'The inner life is the outer map',
    quote: 'Everything that irritates us about others can lead us to understanding ourselves.',
    whyTheyEmbody: "Jung's Wood element gives him growth-oriented depth. His Harmonizer Guardian nature mapped the collective unconscious.",
  },
  {
    slug: 'keanu-reeves',
    name: 'Keanu Reeves',
    born: '1964-09-02',
    knownFor: 'Actor, philanthropist',
    archetype: 'harmonizer_guardian',
    element: 'Wood',
    trait: 'Quiet grace, generosity without fanfare',
    quote: 'I am who I am. I cannot change.',
    whyTheyEmbody: "Reeves' Wood element gives him humble grace. His Harmonizer Guardian nature reminds us that kindness needs no spotlight.",
  },
  {
    slug: 'ray-dalio',
    name: 'Ray Dalio',
    born: '1949-08-08',
    knownFor: 'Bridgewater, investor',
    archetype: 'steady_achiever',
    element: 'Earth',
    trait: 'Principles-first, radical transparency',
    quote: 'Pain plus reflection equals progress.',
    whyTheyEmbody: "Dalio's Earth element gives him principled stability. His Steady Achiever nature built principles that outlast markets.",
  },
  {
    slug: 'charlie-munger',
    name: 'Charlie Munger',
    born: '1924-01-01',
    knownFor: 'Vice chairman, Berkshire',
    archetype: 'steady_achiever',
    element: 'Earth',
    trait: 'Mental models, invert always invert',
    quote: 'Invert, always invert.',
    whyTheyEmbody: "Munger's Earth element gives him principled thinking. His Steady Achiever nature built wealth through mental model mastery.",
  },
  {
    slug: 'tim-cook',
    name: 'Tim Cook',
    born: '1960-11-01',
    knownFor: 'Apple CEO',
    archetype: 'steady_achiever',
    element: 'Metal',
    trait: 'Operational mastery, quiet excellence',
    quote: 'We are the biggest on the planet on privacy.',
    whyTheyEmbody: "Cook's Metal element gives him operational precision. His Steady Achiever nature runs Apple with quiet mastery.",
  },
  {
    slug: 'david-goggins',
    name: 'David Goggins',
    born: '1975-02-17',
    knownFor: 'Author, athlete',
    archetype: 'steady_achiever',
    element: 'Wood',
    trait: 'The 40% rule — you are never truly done',
    quote: 'Stay hard.',
    whyTheyEmbody: "Goggins' Wood element gives him relentless growth. His Steady Achiever nature proves that comfort is the enemy of excellence.",
  },
  {
    slug: 'james-clear',
    name: 'James Clear',
    born: '1986-01-22',
    knownFor: 'Atomic Habits author',
    archetype: 'steady_achiever',
    element: 'Fire',
    trait: '1% better every day, systems over goals',
    quote: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    whyTheyEmbody: "Clear's Fire element gives him transformational energy. His Steady Achiever nature turns atomic habits into lasting change.",
  },
];

export function getFamousProfiles(): FamousProfile[] {
  return profiles;
}

export function getFamousProfileBySlug(slug: string): FamousProfile | undefined {
  return profiles.find((p) => p.slug === slug);
}

export function getFamousProfilesByArchetype(archetype: FamousProfile['archetype']): FamousProfile[] {
  return profiles.filter((p) => p.archetype === archetype);
}
