/**
 * Fallback insight templates — 30 per archetype.
 * Used when the DeepSeek API is unavailable.
 * Templates use {name} as a placeholder (optional).
 */

export type ArchetypeId =
  | 'pioneer'
  | 'sage'
  | 'guardian'
  | 'alchemist'
  | 'luminary'
  | 'architect'
  | 'sovereign'
  | 'mystic'

// Default pool used when archetype is unknown
const DEFAULT_TEMPLATES: string[] = [
  'Every action today compounds into the person you become tomorrow. Choose one thing to do with full intention.',
  'The clearest path forward often appears when you pause and listen to what your energy is telling you.',
  'Small, consistent steps outperform large, sporadic leaps. What one small action moves you forward today?',
  'Your unique combination of strengths is your greatest asset. Lean into what only you can offer.',
  'Rest is productive. Recovery is strategy. Give yourself permission to pause when needed.',
  'The gap between where you are and where you want to be is closed one decision at a time.',
  'Focus is a superpower. Protect it ruthlessly from distractions that do not serve your goals.',
  'What would you do today if you knew success was guaranteed? Start there.',
  'Your patterns reveal your priorities. Does today\'s schedule reflect your deepest values?',
  'Clarity precedes confidence. Before deciding, get clear on what outcome truly matters to you.',
]

const ARCHETYPE_TEMPLATES: Record<ArchetypeId, string[]> = {
  pioneer: [
    'You are built to move fast and break new ground. Today, identify the one bold step that others are afraid to take.',
    'Pioneers thrive at the edge of comfort. Push slightly past yours today — that\'s where breakthroughs live.',
    'Your instinct to lead is a gift. But today, listen before you act. The best pioneers know when to observe.',
    'New beginnings are your element. Is there something you\'ve been hesitating to start? Today is the day.',
    'You excel at initiating. Today, focus on following through on something already started — that\'s where mastery hides.',
    'Pioneers often move so fast they outrun their team. Today, slow down to bring someone with you.',
    'Your energy is infectious. Use it consciously today to lift the room rather than just charge through it.',
    'Bold decisions require clear values. Before acting today, check: does this align with your core mission?',
    'You\'re at your best when creating from scratch. Carve out 30 minutes today for pure, unconstrained thinking.',
    'Every pioneer faces doubt. The difference is acting despite it. What one step can you take despite uncertainty?',
    'Your drive is a feature, not a bug. But check: are you moving toward something, or running from something?',
    'Pioneers need rest to sustain momentum. Schedule recovery as deliberately as you schedule action.',
    'The trail you blaze today becomes the path others walk tomorrow. Make it one worth following.',
    'You see possibilities others miss. Today, articulate your vision clearly — written words make it real.',
    'Momentum is your oxygen. Even a five-minute action toward your goal keeps the fire alive today.',
    'Great pioneers know when to pivot. Is there something you\'re pursuing out of stubbornness that deserves a fresh look?',
    'Your wood energy thrives in growth. Plant something today — a conversation, a habit, an idea — and water it.',
    'You lead best by example. What behavior do you want your team or peers to adopt? Model it visibly today.',
    'Pioneers attract followers naturally. Be intentional about who you\'re inspiring today and toward what.',
    'Speed without direction is chaos. Take two minutes this morning to clarify today\'s primary target.',
    'Your restlessness is information. What is it pointing you toward that you haven\'t yet acknowledged?',
    'The best pioneers study their terrain. Today, research before you rush — preparation accelerates execution.',
    'Breakthrough moments often come after long, invisible work. Trust the process even when the progress is hidden.',
    'You have the courage to begin. Pair it with the discipline to finish — that combination is unstoppable.',
    'Your pioneer spirit inspires others to step up. Who in your life needs a nudge from you today?',
    'Risk is your comfort zone. Make sure today\'s risk is calculated, not impulsive — know your exit before you enter.',
    'The seeds you plant with enthusiasm must be tended with patience. Balance both energies today.',
    'You are wired to create, not maintain. If you\'re stuck managing, delegate — get back to where you spark.',
    'Pioneers shape culture by what they celebrate. Today, acknowledge someone else\'s contribution loudly.',
    'Your legacy is built in the daily choices no one sees. Make today\'s choices legacy-worthy.',
  ],

  sage: [
    'Wisdom is knowing what to ignore. Today, identify one distraction to consciously set aside.',
    'Your gift is depth of understanding. Share an insight with someone who needs it — teaching solidifies your own knowing.',
    'The sage within you already knows the answer. Sit quietly for five minutes and listen.',
    'Knowledge without application is potential, not power. What insight are you ready to put into practice?',
    'You process deeply — but today, trust your first clear thought before you over-analyze.',
    'Your water element flows around obstacles rather than through them. What\'s the elegant path around today\'s challenge?',
    'The sage reads patterns others miss. What recurring theme in your life deserves your full attention now?',
    'Seeking understanding is your strength. But today, move from understanding to decision — clarity through action.',
    'Your mind is your greatest asset. Protect it: curate your inputs carefully today.',
    'Wisdom grows through reflection. Before the day ends, write down one thing you learned about yourself.',
    'The deepest insights come at the intersection of knowledge and lived experience. What are you learning right now?',
    'Sages light the way for others. Who in your circle is struggling with something you\'ve already navigated?',
    'Patience is not passivity — it\'s strategic waiting. Is there something you\'re forcing that needs more time?',
    'Your ability to hold complexity is rare. Today, help someone simplify a decision they\'re overcomplicating.',
    'Great minds are curious minds. Ask one question today that you genuinely don\'t know the answer to.',
    'The sage knows that all knowledge has context. Before judging a situation, gather the full picture.',
    'Your introspective nature is a superpower. Use it today to examine a belief you\'ve never questioned.',
    'Wisdom requires humility. Today, actively seek the perspective of someone whose worldview differs from yours.',
    'You see the long arc of things. Use that lens today to zoom out on a problem that feels urgent but may not be.',
    'Deep thinkers often need deep rest. Prioritize sleep tonight — your insights will be sharper tomorrow.',
    'The sage balances thinking with being. Today, put down the problem and simply observe life for a moment.',
    'Your counsel is valuable. Someone near you is waiting for your input — offer it generously.',
    'What you read shapes how you think. Are your current inputs expanding or narrowing your perspective?',
    'Reflection without action creates rumination. Take one insight from your thinking and act on it today.',
    'The wisest response is often the most measured one. Before reacting today, pause to choose your response.',
    'Your strategic mind sees several moves ahead. Today, map out the second and third order effects of a key decision.',
    'Sages accumulate wisdom from failure as much as from success. What has a recent setback taught you?',
    'Your gift for understanding people makes you a natural mediator. Is there a conflict you could help resolve today?',
    'The sage knows that timing matters as much as truth. Wait for the right moment to share your key insight today.',
    'Depth of character is built in quiet moments. Invest in solitude today — your best ideas live there.',
  ],

  guardian: [
    'Your greatest strength is reliability. Today, identify one commitment you can honor with complete follow-through.',
    'Guardians protect what matters most. Clearly name your top three priorities today — and protect your time accordingly.',
    'Your earth energy creates stability for everyone around you. Who is leaning on you today, and is the weight sustainable?',
    'You are the anchor in your community. Make sure your own foundation is secure before holding others steady.',
    'Consistency is your superpower. The mundane thing you do every day is quietly extraordinary.',
    'You notice when others struggle. Today, reach out to the person who\'s been quietly carrying too much.',
    'Guardians can over-extend in service of others. Check today: are you giving from abundance or from depletion?',
    'Your word is your bond. If you\'ve made a promise you can\'t keep, address it directly and soon.',
    'Security and growth are not opposites. Today, take one calculated risk from a foundation of solid preparation.',
    'Your patience is legendary. Use it today as a strategic asset in a situation where others might rush.',
    'Guardians build for the long term. Today, invest in something whose return comes years from now.',
    'Your loyalty runs deep. Make sure it\'s placed with people and causes that are worthy of it.',
    'You create safety for others to thrive. Is the environment around you — physical and emotional — one that supports growth?',
    'What systems and routines are carrying your best days? Double down on those today.',
    'Guardians sometimes resist change. Today, welcome one small disruption as an opportunity rather than a threat.',
    'Your steadiness in a crisis is a gift. Who is in a storm right now who needs your calm presence?',
    'You protect others instinctively. Today, also protect your own energy, boundaries, and quiet time.',
    'Loyalty without discernment can become limitation. Honestly assess: is every commitment you\'re honoring still aligned with your values?',
    'Your earth energy grounds ideas into reality. Help someone today transform a vague plan into concrete next steps.',
    'Guardians are often the last to ask for help. Today, identify one area where you could use support and ask for it.',
    'Your reliability builds trust over time. That trust is your most valuable professional and personal asset.',
    'The strongest structures have deep foundations. What foundation in your life needs reinforcing right now?',
    'You notice details others miss, especially when something is off. Trust that instinct today.',
    'Service is your nature — make sure it comes from values, not from the fear of letting others down.',
    'Guardians thrive in structured environments. If your environment feels chaotic, spend 15 minutes today restoring order.',
    'Your thoughtful approach prevents costly mistakes. Before a big decision today, consult your internal checklist.',
    'You keep people safe. Who in your life has never heard you say, "I\'ve got you"? Say it today.',
    'Your capacity for endurance is remarkable. Pair it with wisdom about when endurance becomes stubbornness.',
    'The guardian within you is sustained by meaning. Reconnect today with the deeper why behind your daily work.',
    'Small kindnesses repeated become legacies. Your daily acts of care are building something profound.',
  ],

  alchemist: [
    'Transformation is your nature. Today, identify one constraint you\'ve been accepting that you could turn into an advantage.',
    'Alchemists find the hidden value in overlooked things. What have you been dismissing that might be your breakthrough?',
    'You thrive at the intersection of chaos and creativity. Today, enter the mess of an unsolved problem without rushing to fix it.',
    'Your ability to synthesize disparate ideas is rare. Bring two unlikely concepts together and see what emerges.',
    'Alchemists change what they touch. What are you touching today, and what do you want to change about it?',
    'Your fire-metal energy burns through the non-essential to reveal the pure. What can you eliminate today?',
    'Transformation requires heat. Lean into the discomfort of your current growth edge — that\'s where the change happens.',
    'You see potential others overlook. Today, look at your biggest current problem through the lens of hidden opportunity.',
    'Alchemists are often misunderstood. Stop explaining your vision to those who resist it — show them the result instead.',
    'Great transformations begin with a single decision. What is the decision that would change everything for you right now?',
    'You are a catalyst. Your presence accelerates change in others. Be intentional about which direction you\'re pointing them.',
    'The alchemist within you knows: what you resist, persists. What are you avoiding that you need to move through?',
    'Creativity is your fuel. Protect a block of time today for unstructured exploration — no agenda, just curiosity.',
    'You have the ability to turn setbacks into springboards. Look back at a recent failure: what has it given you?',
    'Alchemists work in cycles — creation, dissolution, recreation. Where are you in your current cycle?',
    'Your intuition about what is possible is usually right. Trust it today, especially when logic says otherwise.',
    'Transformation without integration is just change. Today, consolidate a recent shift before pursuing the next.',
    'You are attracted to the novel. Today, apply fresh eyes to something old and familiar — find what you\'ve been missing.',
    'The greatest alchemy happens within. What belief or story about yourself is ready to be transformed?',
    'Alchemists build with what is, not what they wish was. Inventory your actual resources today — they\'re richer than you think.',
    'Your capacity for reinvention is extraordinary. Give yourself permission to be different from who you were last year.',
    'Innovation lives in the question, not the answer. What\'s the best question you can ask about your current challenge?',
    'You thrive on experimentation. Today, run a small test on a big assumption you\'ve been making.',
    'Alchemists never see failure — only data. What has "failed" recently that you\'re ready to reframe as information?',
    'Your unique perspective is your edge. Stop trying to fit the mold — your work is to break it.',
    'Transformation requires courage to release the old before the new is certain. What are you holding onto that needs releasing?',
    'You create breakthroughs for others too. Who in your life is stuck that you could help shift today?',
    'The alchemist\'s secret: the formula always includes patience. Your current transformation is right on schedule.',
    'You change the environment around you just by showing up fully. Show up fully today.',
    'Every great transformation has an invisible period. Trust the process even when — especially when — nothing seems to be happening.',
  ],

  luminary: [
    'Your light is needed today. Show up as the fullest version of yourself — someone is looking to you for inspiration.',
    'Luminaries connect people to possibilities. Today, introduce two people who could spark something extraordinary together.',
    'Your fire energy is magnetic. Channel it toward your highest purpose today — even for just one hour.',
    'You lead through inspiration, not authority. The story you share today could change someone\'s direction forever.',
    'Your presence is your most powerful tool. Be fully present in every conversation today — not just physically, but energetically.',
    'Luminaries shine brightest in the dark. Who around you is struggling, and how can your light reach them today?',
    'Your enthusiasm is contagious. Deploy it deliberately today toward what matters most.',
    'Great communicators know when to listen. Today, balance your radiance with genuine curiosity about others.',
    'You carry a vision that others haven\'t fully seen yet. Today, paint that picture more vividly — in words, in action, in example.',
    'Luminaries can burn bright and burn out. Protect your energy today — rest is how you sustain your light.',
    'Your ability to see and celebrate others\' gifts is a rare talent. Acknowledge someone\'s greatness today.',
    'The impact you\'re having is often greater than you know. Trust that your consistent showing-up matters.',
    'Your optimism is a resource for others. Use it generously today — but also let yourself be real when things are hard.',
    'Luminaries create permission fields — people feel they can grow in your presence. Who needs that permission from you today?',
    'Your charisma is a gift to be used in service. Ask today: am I serving others with my influence, or just enjoying the spotlight?',
    'The best luminaries amplify others\' brightness, not just their own. Who can you lift into the spotlight today?',
    'Your creative fire is at its peak in the morning. Guard those early hours for your most important work.',
    'You inspire people to believe in themselves. Today, be specific — tell someone exactly what you see in them.',
    'Luminaries are often lonely at the front. Build your inner circle deliberately — you need people who challenge you.',
    'Your ability to hold a positive vision even in difficulty is extraordinary. Apply that gift to your most pressing challenge today.',
    'The world needs more light, and you are wired to provide it. Don\'t dim yourself to make others comfortable.',
    'Your energy sets the emotional tone of every room. Today, choose the tone you want to set.',
    'Visibility is your natural state, but vulnerability is your superpower. Share something real today.',
    'Luminaries see beauty in possibility. Today, describe the possibility in someone else\'s situation that they cannot yet see.',
    'Your warmth and radiance draw people to you. Use that trust wisely and repay it with genuine care.',
    'Even the sun sets. Give yourself full permission to rest today without guilt — darkness is part of the cycle.',
    'You are a storyteller by nature. Today, use story to make an idea land that logic alone hasn\'t conveyed.',
    'The luminary within you is sustained by purpose. Reconnect today with the deeper why behind your most visible work.',
    'Your enthusiasm attracts collaborators. Today, articulate your vision with enough specificity that others can join it.',
    'Light multiplies when reflected. Surround yourself today with people who mirror your best self back to you.',
  ],

  architect: [
    'Systems create freedom. Today, design one simple system that will save you time or decision-making this week.',
    'Architects see the whole before the parts. Today, zoom out on your biggest challenge and map the structure beneath it.',
    'Your metal energy cuts through the inessential. What can you eliminate, automate, or delegate to create more clarity?',
    'Great structures begin with a clear vision of the end state. Define your ideal outcome today before choosing your approach.',
    'You build what lasts. Today, invest time in something whose value compounds: a relationship, a skill, a system.',
    'Architects anticipate failure points. Today, run a pre-mortem on a current project — what could go wrong, and how do you prevent it?',
    'Your attention to detail is a gift. Apply it today to the one area most likely to determine your outcome.',
    'Precision is your strength. Today, be precise about what you want — vague goals produce vague results.',
    'You create structure that enables others to thrive. Is the structure around your team clear enough for them to operate without you?',
    'Great architects know when to revise the blueprint. Is there a plan you\'re executing that needs a fundamental rethink?',
    'Your strength is building what endures. Today, check: am I building something real, or just keeping busy?',
    'Architects solve problems before they occur. What future problem can you prevent with a decision made today?',
    'You communicate through structure. Today, organize your most important communication so the logic is impossible to miss.',
    'Constraints are the architect\'s canvas. Take your most significant limitation today and design around it, not against it.',
    'Your systematic mind creates clarity for others. Who in your life is confused right now that you could help organize?',
    'Great builders are also great demolishers. What structure in your life has outlived its usefulness and needs to come down?',
    'You see the load-bearing walls — the elements that truly hold everything up. Identify one in your current project today.',
    'Architects work in phases. Define today\'s phase clearly and resist the urge to jump to the next before this one is complete.',
    'Your ability to translate vision into blueprint is rare. Someone with a great idea needs your help making it concrete today.',
    'The best-designed systems have human needs at their center. Today, test your work against the question: does this serve people?',
    'You build with long time horizons. Today, make one decision that your future self will thank you for.',
    'Great architects iterate. What is the quickest way to get feedback on what you\'re building before you build too much?',
    'Your logic is your compass. Follow it today even when the emotional pull is in a different direction.',
    'Architects need white space on the blueprint. Protect unstructured thinking time today — that\'s where your best designs emerge.',
    'You are drawn to complex problems. Today, break your most complex problem into its smallest solvable components.',
    'The foundation you build today supports everything that comes after. Make it solid.',
    'Architects earn trust through consistency and accuracy. Today, deliver something on time, on spec, with zero errors.',
    'Your blueprint becomes reality through execution. Bridge the gap today — less planning, more building.',
    'Great designs are refined through use. Put something into the hands of users today and learn from their experience.',
    'You see the elegance in a well-designed system. Today, find the inelegance in yours and close the gap.',
  ],

  sovereign: [
    'Leaders do not wait for permission. Today, take responsibility for one area of your life that you\'ve been treating as outside your control.',
    'Sovereignty begins within. Today, clarify the non-negotiable values that guide every decision you make.',
    'Your authority comes from integrity, not title. Today, make a decision that demonstrates what you truly stand for.',
    'Sovereigns create the conditions for others to flourish. Look around today: are your people thriving?',
    'Your strategic mind sees the board three moves ahead. Map out the consequence chain of today\'s most important decision.',
    'True leaders take responsibility for outcomes, not just intentions. Where does accountability stop with you and not get passed on?',
    'Sovereignty requires the courage to hold the unpopular position. What do you know to be true that you haven\'t said aloud yet?',
    'Great leaders develop other leaders. Who on your team is ready for more responsibility? Give it to them today.',
    'Your composure under pressure is your most visible leadership quality. Someone is watching how you handle today\'s challenge.',
    'Sovereigns serve their kingdom. Check today: are you leading for the people you serve, or for your own ego?',
    'The weight of responsibility you carry is real. Make sure you have someone you can be honest with about the burden.',
    'Your decisiveness is valued, but today, slow down a major decision long enough to gather one more crucial input.',
    'Sovereigns speak last in the room. Today, ask more questions than you answer.',
    'Your legacy is the culture you create. What behavior, if practiced consistently, would define the culture you want?',
    'Great leaders know their own shadow side. Today, ask yourself: when am I at my worst, and what triggers it?',
    'Sovereignty requires vision. Write down today where you want to be in five years — be specific and honest.',
    'Your presence commands attention. Use it today to direct focus toward what truly matters.',
    'Sovereigns hold the long view. Today, make one decision that sacrifices short-term comfort for long-term strength.',
    'The best leaders create other leaders, not followers. Today, empower instead of direct.',
    'Your capacity to absorb difficulty without breaking is extraordinary. Make sure you\'re replenishing that capacity.',
    'Sovereigns know that delegation is not weakness — it\'s leverage. What are you still doing that someone else should own?',
    'Your vision is your north star. Today, check: are your daily actions aligned with the future you\'re building toward?',
    'Great leaders listen at depth. Today, hear not just what someone says, but what they mean and what they need.',
    'Sovereignty includes the sovereignty of others. Today, give someone full ownership over something and resist the urge to micromanage.',
    'Your decisions ripple outward. Today, spend extra care on the one decision whose effects will be felt most widely.',
    'Sovereigns build alliances, not just teams. Who do you need to build a stronger relationship with today?',
    'The measure of your leadership is who leads when you\'re not in the room. Build that capacity deliberately.',
    'Your strategic patience is an asset. Not everything needs to be resolved today — some things need to ripen.',
    'Great leaders own their mistakes publicly and learn from them privately. Is there something to own today?',
    'Your authority is earned and re-earned daily. What will you do today to deserve the trust placed in you?',
  ],

  mystic: [
    'Your intuition is a form of intelligence. Today, follow one instinct that you can\'t fully explain — trust it.',
    'Mystics navigate by inner knowing. Before making a decision today, sit with it in silence and feel, not just think, your answer.',
    'You perceive the invisible currents beneath the surface. What pattern are you sensing in your current situation that needs attention?',
    'Your water energy flows naturally around resistance. Today, stop pushing and find the path of least resistance to your goal.',
    'The mystic within you sees beyond the obvious. Today, question the obvious explanation for something that\'s been bothering you.',
    'Connection is your nature — to people, to ideas, to meaning. Seek one meaningful connection today that fills you.',
    'Your sensitivity is a gift, not a burden. Today, let yourself fully feel — that depth of experience is data.',
    'Mystics renew in solitude. Schedule genuine alone time today — not rest, but presence with yourself.',
    'You perceive what others project but don\'t say. Today, respond to what someone really means, not just their words.',
    'Your dreams and hunches carry information. Before you dismiss a quiet knowing, explore it.',
    'Mystics work in the realm of meaning. Today, ask: what does this situation mean at the deepest level?',
    'Your empathy creates deep bonds. Make sure those bonds are reciprocal — do the people close to you give as they receive?',
    'You sense energetic shifts before they become visible. What shift are you sensing in your environment right now?',
    'The mystic within you understands cycles. Where are you in the current cycle of your most important endeavor?',
    'Your inner landscape is as real as the outer world. Tend to it today with the same care you give to external demands.',
    'You perceive the sacred in the ordinary. Today, move slowly enough through your day to notice the moments of beauty.',
    'Mystics make meaning from chaos. What story are you currently living that needs a deeper narrative?',
    'Your gift for non-linear thinking breaks through where sequential thinking gets stuck. Apply it to your current obstacle.',
    'You process experience deeply and slowly. Give yourself permission to not have the answer yet — let it come.',
    'Mystics often know things before they can explain why. Trust that knowing today even without the explanation.',
    'Your sensitivity to subtlety makes you a rare communicator when you choose to articulate what you sense.',
    'The unseen is often more important than the seen. Today, pay attention to what\'s absent in a key situation.',
    'Your inner world is rich. Share a glimpse of it with someone who has earned the privilege of that depth.',
    'Mystics hold space for mystery. Today, resist the urge to prematurely resolve something that needs more time to unfold.',
    'You feel before you think — honor that sequence. Check in with your body\'s wisdom before your mind\'s analysis.',
    'Your gift for seeing beneath the surface makes you invaluable in conflict. Help someone see what\'s really happening today.',
    'The mystic within you is nourished by beauty. Today, deliberately encounter something beautiful — art, nature, music, a face.',
    'You absorb the energy of your environment deeply. Choose your surroundings today with extra care.',
    'Your depth of perception is rare. Use it today to help someone understand themselves better than they currently do.',
    'Mystics live at the boundary between worlds. That liminal space is where your best insights emerge — visit it intentionally today.',
  ],
}

/**
 * Get a random fallback template for the given archetype.
 * Uses date-seeded selection for consistent daily variation.
 */
export function getFallbackInsight(archetypeId: string, dateStr: string): string {
  const pool = ARCHETYPE_TEMPLATES[archetypeId as ArchetypeId] ?? DEFAULT_TEMPLATES
  // Deterministic daily selection using date hash
  let hash = 0
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) & 0xfffffff
  }
  return pool[hash % pool.length]
}
