import type { DomainMeta } from './types'

export const DOMAINS: DomainMeta[] = [
  {
    id: 'career',
    label: 'Career',
    icon: '🚀',
    color: '#3b82f6',
    accent: '#1d4ed8',
    description: 'Professional growth, skills, and impact',
    promptHint: 'What do you want to achieve professionally?',
    defaultCheckMethod: 'milestone',
    suggestions: [
      'Get promoted to senior engineer',
      'Launch a successful product',
      'Build a 10-person team',
      'Speak at a major conference',
      'Earn $X in annual revenue',
    ],
  },
  {
    id: 'wealth',
    label: 'Wealth',
    icon: '💎',
    color: '#f59e0b',
    accent: '#d97706',
    description: 'Financial freedom, investment, and security',
    promptHint: 'What financial milestone are you working toward?',
    defaultCheckMethod: 'numeric',
    suggestions: [
      'Save $100k in investments',
      'Pay off all debt',
      'Generate $5k/month passive income',
      'Build a 6-month emergency fund',
      'Start a profitable side business',
    ],
  },
  {
    id: 'health',
    label: 'Health',
    icon: '⚡',
    color: '#10b981',
    accent: '#059669',
    description: 'Physical vitality, mental wellbeing, and longevity',
    promptHint: 'What health outcome do you want to achieve?',
    defaultCheckMethod: 'streak',
    suggestions: [
      'Run a marathon',
      'Meditate daily for a year',
      'Lose 20 pounds',
      'Sleep 8 hours every night',
      'Bench press my body weight',
    ],
  },
  {
    id: 'relationships',
    label: 'Relationships',
    icon: '🤝',
    color: '#ec4899',
    accent: '#db2777',
    description: 'Deep connections, love, and community',
    promptHint: 'What relationship goal matters most to you?',
    defaultCheckMethod: 'binary',
    suggestions: [
      'Have a weekly date night',
      'Call family every week',
      'Build a 20-person inner circle',
      'Find a life partner',
      'Mentor 3 people this year',
    ],
  },
  {
    id: 'learning',
    label: 'Learning',
    icon: '🧠',
    color: '#8b5cf6',
    accent: '#7c3aed',
    description: 'Knowledge, mastery, and intellectual growth',
    promptHint: 'What skill or knowledge area do you want to master?',
    defaultCheckMethod: 'milestone',
    suggestions: [
      'Become fluent in Spanish',
      'Read 52 books this year',
      'Complete an MBA',
      'Master machine learning',
      'Learn to play the piano',
    ],
  },
  {
    id: 'legacy',
    label: 'Legacy',
    icon: '🌍',
    color: '#f97316',
    accent: '#ea580c',
    description: 'Impact, purpose, and what you leave behind',
    promptHint: 'What lasting impact do you want to create?',
    defaultCheckMethod: 'milestone',
    suggestions: [
      'Write a book that helps 100k people',
      'Start a foundation or nonprofit',
      'Create 1000 jobs',
      'Build a school in a developing country',
      'Leave a $1M endowment',
    ],
  },
]

export function getDomain(id: string): DomainMeta | undefined {
  return DOMAINS.find(d => d.id === id)
}
